name: csharp_dev

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-csharp_dev}
      POSTGRES_USER: ${POSTGRES_USER:-csharp_dev}
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  web:
    image: csharp:dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
