name: csharp_dev

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-csharp_dev}
      POSTGRES_USER: ${POSTGRES_USER:-csharp_dev}
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network  

  redis:
    image: redis:latest

  web:
    image: csharp:dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
      - redis
    expose:
      - "5000"  
    networks:
      network:        
        aliases:
          - csharp
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:  
